# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rake"
gem "pry"
gem "yard-doctest"
gem "rspec"
gem "priority_queue_cxx"
gem "benchmark-ips"
gem "matrix"

gem "debug"
gem "ruby-lsp", "~> 0.3.7", group: :development
